### ISSUE TITLE
Pagination links and request hashes (HMAC)

### ISSUE THREAD

**Issue by frau-liessmann** [dwenzel/t3events#43] opened 2016-06-27 13:09 UTC
When adding 'addQueryStringMethod' to the template of paginate widget and clicking a paginate link I get a frontend error:
`Uncaught TYPO3 Exception #1320830018: The given string was not appended with a valid HMAC.`

I can reproduce this with version 0.19.0, 0.20.0 and 0.21.0.

I extracted this Issue from #39 .

**Comment by dwenzel** [comment] 2016-07-11 20:03
In version (0.25.0) the extension of the PaginationWidget has been removed from t3events. So we now use the vanilla Pagination widget and template from fluid. I could not reproduce this issue in current projects with TYPO3 6.2 and 7.6.

**Comment by dwenzel** [comment] 2016-07-15 20:00
should be fixed - close it?

**Comment by frau-liessmann** [comment] 2016-07-21 09:59
No, unfortunately the HMAC error still occurs in frontend.

**Comment by dwenzel** [comment] 2016-07-21 19:58
Ok, I guess, you added a request argument to the action link which was not present in the original post (of the filter form). The hash service complains about this unknown argument. You could try adding an hidden field with this value to the form - but I doubt it will work (because your argument will not have the right path then: the quickMenu plugin sends an overrideDemand array...

**Closed** 2016-11-16 06:35 UTC
Labels: bug, invalid
